### PR TITLE
Upgrade repo

### PR DESCRIPTION
**Pull request by LuisMunozVillarreal**

### CODE REVIEW

**Comment by HelloThisIsFlo** [comment]
Hey @LuisMunozVillarreal 

Thanks a lot for your PR. I've had a project on the back burner to bring this project up-to-date, it seems your PR is doing just that. 🙂

Does it make it compatible with the latest Appdaemon/HomeAssistant? 

I haven't used this tool in a long time so I'm a bit out of touch.

Also, why did you close it? 🤔

If your PR makes this project compatible with the latest versions of Appdaemon, it could save me a lot of time, thanks 👍 However, all the formatting and folder renaming changes make it a bit difficult to quickly see what changed. I'll take a deeper look at some point. Also, I'm using Pipenv and not Poetry, but I'm willing to discover new tools. What's the advantage of Poetry over Pipenv?

This project is not my top priority at the moment, but I aim to look at it a bit more in depth in the next 4-8 weeks.

**Comment by LuisMunozVillarreal** [comment]
Hey @HelloThisIsFlo,

I meant to make the PR against my fork since you say in other PRs that this repo was unmaintaned. That's why I closed it once I realised.

This PR makes it compatible with the latest `appdaemon`. I did a lot other changes as you can see. I easy way to see them in isolation is to check commit by commit, rather than the whole PR.

I've also developed a couple more features in my fork:
1. New helper `when`, that triggers the callbacks that are listening to sensors. 
1. Ability to initialise automations with arguments (like if it were coming from the yaml).

The only thing remaining to do is updating the docs and the README to reflect all the above.

If you're considering to maintain the repo again, we can look into merge those changes into this repo.

Regarding `poetry`. I used to use `requirements.txt` in other projects and thought that it was time for a change. I checked comparison online, like [this one](https://plainenglish.io/blog/poetry-a-better-version-of-python-pipenv); and chose `poetry` instead of `pipenv`.

Cheers,
Luis

**Comment by HelloThisIsFlo** [comment]
Oh I see, that make sense why you would use `poetry` and change a lot of the formatting, this PR originally intended for personal use.

Still, I think going through your commits instead of figuring out the fixes to do on my own is going to save me a **lot** of time when I finally get around to updating this project. So thanks a lot 😃. 

I may redo a separate PR however, without the formatting changes and possibly without poetry. But I'll make sure to cherry pick as many commits from your PR as possible, so you get credit for your hard work 🙂👍

Regarding formatting, I may have a separate PR where I format the whole project with Black. It's opinionated, but it has the advantage of being a one-click solution. Did you use Black? Or any other formatting tool?

Similarly, I'll look into Poetry, and the link you sent me. if it's a better alternative to Pipenv, I may have another PR to use that instead. And another one for your new helper & initialization (or you could open a PR yourself if you prefer, once we're done with the other changes)

But again, this project is not my priority at the moment, so don't expect anything anytime soon. Still, thanks a lot for your contribution 😃 I'll update you once I get some progress on this

**Comment by LuisMunozVillarreal** [comment]
No worries. Happy to help

The tools I use for code formatting and standards are: `flake8`, `black`, `mypy`, `pylint` and `pydocstyle`. I'm not enforcing them all in my fork just yet, as you can see [here](https://github.com/LuisMunozVillarreal/appdaemon-test-framework/blob/main/.circleci/config.yml); but that'd be the idea in the future.

Happy to open PRs to merge functionality once you come back to do some changes here.

Cheers

**Comment by HelloThisIsFlo** [comment]
Hey,
Quick update. I, unfortunately, couldn't find the time to prioritize this PR. I seem to live in a constant state of "too many things to do" 😅.
If I find time to work on this PR in the next few months, I'll be sure to keep you updated 👍 Still, thanks again for your contribution, it's very appreciated!

**Comment by LuisMunozVillarreal** [comment]
Hey @HelloThisIsFlo. No worries, man. Thanks for the tool!

**Pull request closed without merging**
